## 판다스 자료구조

In [1]:
import pandas as pd

### 1. Series

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
type(obj)

pandas.core.series.Series

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index  # range(4)와 유사

RangeIndex(start=0, stop=4, step=1)

In [8]:
type(obj.values)

numpy.ndarray

In [7]:
type(obj.index)

pandas.core.indexes.range.RangeIndex

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
type(obj2.index)

pandas.core.indexes.base.Index

In [12]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [13]:
type(obj2.values)

numpy.ndarray

In [15]:
import numpy as np
a = np.array([1, 2, 3, 4])
a[0]

1

In [16]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [17]:
obj[0]

4

In [18]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [20]:
obj2['d']

4

In [22]:
obj2['a']

-5

In [23]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [25]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [26]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [27]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [28]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [29]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [30]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [31]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [32]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [34]:
'b' in obj2

True

In [35]:
'e' in obj2

False

In [36]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [37]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [48]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [49]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [50]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [51]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [52]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [53]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [54]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [55]:
obj4.name = "population"
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [56]:
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [57]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [58]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 2. DataFrame

In [59]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [60]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [61]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [62]:
frame.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

In [63]:
type(frame.values)

numpy.ndarray

In [65]:
frame.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [66]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [67]:
pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'])

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [92]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
            index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [93]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [94]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [95]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [96]:
type(frame2['state'])

pandas.core.series.Series

In [97]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [98]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [99]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [100]:
frame2.loc['one']

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [101]:
type(frame2.loc['one'])

pandas.core.series.Series

In [102]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [103]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [104]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [105]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [106]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [107]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [108]:
frame2.state == 'Ohio'

one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool

In [109]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [111]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [112]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [113]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [114]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [115]:
frame3['Ohio'][:-1]

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [ ]:
frame3['Nevada'][:2]

In [116]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
        'Nevada' : frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [117]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [118]:
frame3.name = "population"
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [119]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [120]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [121]:
frame3.values.dtype

dtype('float64')

In [122]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [123]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [127]:
frame2.columns.dtype

dtype('O')

### 3. Index

In [131]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [132]:
index[1:]

Index(['b', 'c'], dtype='object')

In [133]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [134]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [135]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [137]:
obj2.index is labels

True

In [138]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [139]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [140]:
'Ohio' in frame3.columns

True

In [141]:
2003 in frame3.index

False

In [142]:
pd.Index(['foo', 'foo', 'bar', 'bar'])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### 실습

* 딕셔너리-> 시리즈 변환 (index, values 출력)

In [143]:
dict_data = {'a': 1, 'b': 2, 'c': 3}

In [144]:
sr = pd.Series(dict_data)
sr

a    1
b    2
c    3
dtype: int64

In [145]:
sr.index

Index(['a', 'b', 'c'], dtype='object')

In [146]:
sr.values

array([1, 2, 3], dtype=int64)

* 리스트 -> 시리즈 변환 (index, values 출력)

In [147]:
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]

In [148]:
sr = pd.Series(list_data)
sr

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [149]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [150]:
sr.values

array(['2019-01-02', 3.14, 'ABC', 100, True], dtype=object)

* 튜플 -> 시리즈 변환 (index, values 출력)

In [151]:
tup_data = ('영인', '2010-05-01', '여', True)

In [152]:
sr = pd.Series(tup_data)
sr

0            영인
1    2010-05-01
2             여
3          True
dtype: object

In [153]:
sr.index

RangeIndex(start=0, stop=4, step=1)

In [154]:
sr.values

array(['영인', '2010-05-01', '여', True], dtype=object)

* 튜플 -> 시리즈 변환 (index 설정)

In [155]:
tup_data = ('영인', '2010-05-01', '여', True)
index_name=['이름', '생년월일', '성별', '학생여부']

In [156]:
sr = pd.Series(tup_data, index=index_name)
sr

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

* 시리즈 원소 선택

In [157]:
tup_data = ('영인', '2010-05-01', '여', True)
index_name=['이름', '생년월일', '성별', '학생여부']

In [158]:
sr = pd.Series(tup_data, index=index_name)
sr

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [ ]:
# 색인을 통해 '영인' 값 얻어오기

In [159]:
sr[0]

'영인'

In [160]:
sr['이름']

'영인'

In [ ]:
# 색인(슬라이싱)을 통해 ''2010-05-01'과 '여' 선택하기

In [161]:
sr[[1, 2]]

생년월일    2010-05-01
성별               여
dtype: object

In [162]:
sr[['생년월일', '성별']]

생년월일    2010-05-01
성별               여
dtype: object

In [164]:
sr[1 : 3]

생년월일    2010-05-01
성별               여
dtype: object

In [165]:
sr['생년월일' : '성별']

생년월일    2010-05-01
성별               여
dtype: object

* 딕셔너리->데이터프레임 변환

In [166]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

In [167]:
df = pd.DataFrame(dict_data)
df

c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

* 행인덱스/ 열 이름 설정

In [168]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
# 준서, 예은 -> '학생1', '학생2'

In [169]:
df.index=['학생1', '학생2']

In [170]:
df

나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [ ]:
# 나이, 성별, 학교 -> '연령', '남녀', '소속'

In [174]:
df.columns = ['연령', '남녀', '소속']

In [172]:
df

연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [ ]:
* 행인덱스/ 열 이름 변경

In [176]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
# rename 사용하여 변경

In [177]:
df.rename(columns = {'나이':'연령', '성별':'남녀', '학교':'소속' }, inplace=True)

연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [178]:
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [179]:
df.rename(index = {'준서':'학생1', '예은':'학생2' }, inplace=True)

나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [180]:
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

## 중요한 기능들

### 1. 재색인 

In [181]:
obj = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [182]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [183]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [186]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [187]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [188]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [189]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [191]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [190]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 2. 로우나 컬럼 삭제하기

In [196]:
obj = pd.Series(np.arange(5), index= ['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [197]:
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int32

In [198]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [199]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int32

In [203]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index = ['Ohio', 'Colorado', 'Utah', 'New York'],
            columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [204]:
data.drop('Colorado')

one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [206]:
data.drop(['Colorado', 'Ohio'], axis='index')

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [208]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [209]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [210]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [211]:
obj.drop('c', inplace=True)
obj

a    0
b    1
d    3
e    4
dtype: int32

* 축에 대해 연산을 할 때 

일반적으로는 "그 축을 따라서" 연산
삭제하는 경우에는 "그 축을" 삭제

### 3. 색인하기, 선택하기, 거르기

In [224]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [225]:
obj['b']

1.0

In [226]:
obj[1]

1.0

In [227]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [228]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [229]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [230]:
obj < 2

a     True
b     True
c    False
d    False
dtype: bool

In [231]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [232]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [233]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [234]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [236]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index = ['Ohio', 'Colorado', 'Utah', 'New York'],
            columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [237]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [238]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [239]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [240]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [241]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [243]:
data[data < 5] = 0

In [244]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

* loc, iloc 선택하기

In [245]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [246]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [247]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [248]:
data.iloc[1, [1, 2]]

two      5
three    6
Name: Colorado, dtype: int32

In [249]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [250]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [252]:
data.loc['Utah']

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [254]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [255]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [256]:
data.three > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [257]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 4. 정수 색인

In [258]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [259]:
ser[:1]

0    0.0
dtype: float64

In [260]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [261]:
ser.iloc[:1]

0    0.0
dtype: float64

### 실습

* 행삭제

In [263]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준' 행 삭제

In [264]:
df.drop('서준')

수학  영어   음악  체육
우현  80  89   95  90
인아  70  95  100  90

In [ ]:
# '서준', '우현' 행 삭제

In [265]:
df.drop(['서준', '우현'])

수학  영어   음악  체육
인아  70  95  100  90

* 열삭제

In [266]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '수학' 열 삭제

In [267]:
df.drop('수학', 1)

영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [268]:
# '수학', '영어' 열 삭제

In [269]:
df.drop(['수학','영어'],1)

음악   체육
서준   85  100
우현   95   90
인아  100   90

*  행선택

In [270]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준' 행 선택 (라벨 색인, 정수 색인)

In [271]:
df.loc['서준']

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [272]:
df.iloc[0]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [ ]:
# '서준', '우현' 행 선택(라벨 색인, 정수 색인, 슬라이싱)

In [273]:
df.loc[['서준', '우현']]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [274]:
df.iloc[[0,1]]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [275]:
df.loc['서준':'우현']

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [277]:
df.iloc[0:2]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

* 열선택

In [278]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '수학' 열 선택

In [279]:
df['수학']

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [280]:
df.수학

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [ ]:
# '음악', '체육' 열 선택

In [281]:
df[['음악','체육']]

음악   체육
서준   85  100
우현   95   90
인아  100   90

In [ ]:
# 참고

In [282]:
df['수학']

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [283]:
df[['수학']]

수학
서준  90
우현  80
인아  70

* 원소 선택

In [284]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준'의 '음악' 점수

In [285]:
df.loc['서준', '음악']

85

In [286]:
df.iloc[0,2]

85

In [ ]:
#'서준'의 '음악','체육' 점수

In [287]:
df.loc['서준', ['음악', '체육']]

음악     85
체육    100
Name: 서준, dtype: int64

In [288]:
df.iloc[0,[2,3]]

음악     85
체육    100
Name: 서준, dtype: int64

In [ ]:
#'서준','우현'의 '음악','체육' 점수

In [289]:
df.loc[['서준', '우현'], ['음악', '체육']]

음악   체육
서준  85  100
우현  95   90

In [290]:
df.iloc[[0, 1], [2, 3]]

음악   체육
서준  85  100
우현  95   90

* 열추가

In [317]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '국어' 열 추가, 값은 80 점 지정

In [318]:
df['국어'] = 80
df

수학  영어   음악   체육  국어
서준  90  98   85  100  80
우현  80  89   95   90  80
인아  70  95  100   90  80

* 행추가

In [319]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# "본인 이름" 으로 행추가, 과목 점수도 지정

In [320]:
df.loc['경희'] = [100,90,80,70]
df

수학  영어   음악   체육
서준   90  98   85  100
우현   80  89   95   90
인아   70  95  100   90
경희  100  90   80   70

* 원소값 변경

In [321]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [293]:
# '서준'의 '체육' 점수를 80 점으로 변경(라벨 색인, 정수 색인)

In [322]:
df.loc['서준', '체육'] = 80
df

수학  영어   음악  체육
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [323]:
df.loc['서준']['체육'] = 70
df

수학  영어   음악  체육
서준  90  98   85  70
우현  80  89   95  90
인아  70  95  100  90

In [324]:
df.iloc[0, 3] = 80
df

수학  영어   음악  체육
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [325]:
df.iloc[0][3] = 70
df

수학  영어   음악  체육
서준  90  98   85  70
우현  80  89   95  90
인아  70  95  100  90

In [ ]:
# '서준'의 '음악','체육' 점수 변경

In [326]:
df.loc['서준', ['음악', '체육']] = 100, 100
df

수학  영어   음악   체육
서준  90  98  100  100
우현  80  89   95   90
인아  70  95  100   90

In [327]:
df.iloc[0, [2,3]] = 90, 90
df

수학  영어   음악  체육
서준  90  98   90  90
우현  80  89   95  90
인아  70  95  100  90

In [328]:
df.loc['서준'][['음악', '체육']] = 100, 100
df

수학  영어   음악   체육
서준  90  98  100  100
우현  80  89   95   90
인아  70  95  100   90

* 행, 열 바꾸기

In [329]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# 과목이 행, 학생이 열

In [330]:
df.T

서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [331]:
df.transpose()

서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

* 특정 열을 행 인덱스로 설정

In [332]:
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70],
             '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100],
             '체육' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data)
df

이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [309]:
# '이름' 열을 행 인덱스로 시정 

In [335]:
df.set_index(['이름'], inplace = True)

In [338]:
# reindex

In [336]:
df

수학  영어   음악   체육
이름                  
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [337]:
df.reindex(['인아', '서준', '경희'])

수학    영어     음악     체육
이름                          
인아  70.0  95.0  100.0   90.0
서준  90.0  98.0   85.0  100.0
경희   NaN   NaN    NaN    NaN

In [339]:
df

수학  영어   음악   체육
이름                  
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# reset_index

In [340]:
df.reset_index()

이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

### 5. 산술 연산과 데이터 정렬

In [342]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [343]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [344]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [345]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [346]:
df1 = pd.DataFrame({'A' : [1, 2]})
df2 = pd.DataFrame({'B' : [3, 4]})

In [347]:
df1

A
0  1
1  2

In [348]:
df2

B
0  3
1  4

In [349]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [386]:
df1 = pd.DataFrame(np.arange(12).reshape(3, 4), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape(4, 5), columns = list('abcde'))
df2.loc[1, 'b'] = np.nan

In [387]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [388]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [389]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [390]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [391]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [392]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [393]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [394]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [395]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [364]:
df1.reindex(columns=df2.columns)

a  b   c   d   e
0  0  1   2   3 NaN
1  4  5   6   7 NaN
2  8  9  10  11 NaN

In [365]:
df1.reindex(columns=df2.columns, fill_value = 0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

* (참고) 넘파이 산술연산 예

In [367]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [368]:
arr[0]

array([0., 1., 2., 3.])

In [369]:
arr * 2

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [370]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
* 데이터프레임 산술연산 예

In [373]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
            columns = list('bde'),
            index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

series = frame.iloc[0]

In [374]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [375]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [376]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [378]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [379]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [380]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [396]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [397]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [401]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 실습

In [402]:
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student1

국어    100
영어     80
수학     90
dtype: int64

In [ ]:
# 과목별 점수를 100으로 나누기

In [404]:
student1/100

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [405]:
student1.div(100)

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [407]:
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

In [408]:
# 두 학생의 평균
(student1 + student2)/2

국어    95.0
수학    85.0
영어    80.0
dtype: float64

In [409]:
student1.add(student2).div(2)

국어    95.0
수학    85.0
영어    80.0
dtype: float64

In [411]:
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

In [412]:
# 두 학생의 평균
(student1 + student2)/2

국어     NaN
수학    85.0
영어     NaN
dtype: float64

In [413]:
student1.add(student2, fill_value=0).div(2)

국어    45.0
수학    85.0
영어    40.0
dtype: float64